### ISSUE TITLE
[BUG] Issue clearing config files

### ISSUE THREAD

**Issue by Ghmichael2** [R3alCl0ud/Rust4Diva#25]
**Describe the bug:**
When using the reload button when on all mods it will clear the config file of mods that have more than 
Enabled
Name
Description 
Version
Date
Author
Include

**To Reproduce:**
Have any mods such as x ui, or opening replacements, 

**Expected behavior:**
Not get rid of any extra settings for a mod in the config file

**Screenshots (Optional but helpful):**

**Useful info:**
 - OS: [e.g. Windows 10, Linux, MacOS]
 - Rust4Diva Version (can be found in `About Rust4Diva` since 0.4.0): 
Linux (steam deck)
Flatpack Version 0.4.1

**Additional context:**
If there is an issue with a specific mod please link it here:
https://gamebanana.com/mods/417506
https://gamebanana.com/mods/383491

**Comment by R3alCl0ud** [comment]
Ok, I understand exactly what you meant now, with how it's programmed this is expected behavior actually. This is because those mods are using extra fields in their `config.toml` that aren't actually part of the DML standard (name, version, descrition, etc also are not part of the standard either btw.

The fields I currently recognize in the code are:
```rs
pub struct DivaModConfig {
    pub enabled: bool,
    pub include: Vec<String>,
    pub dll: Vec<String>,
    pub name: String,
    pub description: String,
    pub version: String,
    pub date: String,
    pub author: String,
}
```
To fix this is going to take some time and is going to be a huge refactor since I'll have to use sonic_rs's JsonObject feature instead of deserializing to a statically typed struct.
